#!/usr/bin/env node
import { existsSync } from "node:fs";
import { readFile, readdir } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const ROOT = join(__dirname, "..");
const SKILLS_DIR = join(ROOT, "skills");
const MANIFEST_PATH = join(ROOT, "docs", "manifest.json");

function toPosix(path) {
  return path.split(sep).join("/");
}

function fail(errors, message) {
  errors.push(message);
}

function markdownLinks(content) {
  return [...content.matchAll(/\[[^\]]+\]\(([^)]+)\)/g)].map((match) => match[1]);
}

async function checkLocalLinks(errors, file) {
  const content = await readFile(file, "utf8");
  for (const link of markdownLinks(content)) {
    if (
      link.includes("://") ||
      link.startsWith("#") ||
      link.startsWith("mailto:")
    ) {
      continue;
    }
    const target = resolve(dirname(file), link.split("#")[0]);
    if (!existsSync(target)) {
      fail(errors, `${toPosix(relative(ROOT, file))}: missing local link ${link}`);
    }
  }
}

async function main() {
  const manifest = JSON.parse(await readFile(MANIFEST_PATH, "utf8"));
  const errors = [];
  const checkedDocs = [
    join(ROOT, "README.md"),
    join(ROOT, "CONTRIBUTING.md"),
    join(ROOT, "SKILLS.md"),
    join(ROOT, "docs", "skills-mcp.md"),
    join(SKILLS_DIR, "README.md"),
  ];

  const categoryDirs = (await readdir(SKILLS_DIR, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();

  for (const category of manifest.categories) {
    const readme = join(SKILLS_DIR, category, "README.md");
    if (!existsSync(readme)) {
      fail(errors, `skills/${category}/README.md: missing category README`);
      continue;
    }
    checkedDocs.push(readme);
    const content = await readFile(readme, "utf8");
    if (!content.includes("<!-- generated:category-readme -->")) {
      fail(errors, `skills/${category}/README.md: not generated by build-manifest.mjs`);
    }
    const skills = manifest.skills.filter((skill) => skill.category === category);
    for (const skill of skills) {
      if (!content.includes(`\`${skill.install_path}\``)) {
        fail(errors, `skills/${category}/README.md: missing ${skill.install_path}`);
      }
    }
  }

  for (const category of categoryDirs) {
    if (!manifest.categories.includes(category)) {
      fail(errors, `skills/${category}: category directory is absent from manifest`);
    }
  }

  for (const skill of manifest.skills) {
    const skillFile = join(ROOT, skill.path, "SKILL.md");
    if (!existsSync(skillFile)) {
      fail(errors, `${skill.path}/SKILL.md: manifest entry points to missing file`);
    }
  }

  const skillsReadme = await readFile(join(SKILLS_DIR, "README.md"), "utf8");
  if (!skillsReadme.includes(`**Total:** ${manifest.count} skills across ${manifest.categories.length} categories.`)) {
    fail(errors, "skills/README.md: stale total skill or category count");
  }
  for (const category of manifest.categories) {
    if (!skillsReadme.includes(`[\`${category}\`](./${category}/)`)) {
      fail(errors, `skills/README.md: missing category ${category}`);
    }
  }

  const rootReadme = await readFile(join(ROOT, "README.md"), "utf8");
  if (!rootReadme.includes(`**${manifest.count} Agent Skills** across **${manifest.categories.length} categories**`)) {
    fail(errors, "README.md: stale total skill or category count");
  }
  for (const category of manifest.categories) {
    if (!rootReadme.includes(`[\`${category}\`](./skills/${category}/)`)) {
      fail(errors, `README.md: missing category ${category}`);
    }
  }

  const skillsIndex = await readFile(join(ROOT, "SKILLS.md"), "utf8");
  for (const skill of manifest.skills) {
    if (!skillsIndex.includes(`./${skill.path}/SKILL.md`)) {
      fail(errors, `SKILLS.md: missing ${skill.install_path}`);
    }
  }

  for (const doc of checkedDocs) {
    await checkLocalLinks(errors, doc);
  }

  if (errors.length) {
    console.error(`Documentation audit failed with ${errors.length} issue(s):`);
    for (const error of errors) console.error(`  - ${error}`);
    process.exit(1);
  }

  console.log(`OK  ${manifest.count} skills documented`);
  console.log(`OK  ${manifest.categories.length} category READMEs current`);
  console.log(`OK  root and skills indexes current`);
  console.log(`OK  generated documentation links resolve`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
